### ISSUE TITLE
Feature: User can set their one rep max

### ISSUE THREAD

**Issue by tangm28** [tangm28/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can set their 1 rep max for their Bench, Squat, Deadlift, and Overhead Press.
User can use the 1 rep max calculator to find their approximate 1 rep max

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Text input box to enter a valid number with a dropdown box to select either lb or kg
Save button for user to save information.
Hyperlink in description to 1 Rep Max Calculator Modal
User can enter weight number, lb/kg, and number of reps to find max
User can exit out of the modal with the x icon on top right of modal or the Got It! button after getting a calculation

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749849/148308902-1088abf5-b1f3-4a1e-8ab1-f0a1ab93347e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create Header with app title "Workout Journal"
- [x] Create container for app
- [x] Create layout for 1 rep max
- [x] Add text input for user to input numbers
- [x] Add dropdown box so user can only select lb or kg
- [x] In description text, add a text hyperlink to 1 Rep Max Calculator Modal
  - [x] Create overlay that covers entire screen
  - [x] Create modal for user to input weight, dropdown for lb or kg, and input numbers of reps
  - [x] Replace calculator modal view with view of the user's approximate 1 rep max
  - [x] Return back to Let's Get Started page
  - [x] When user hit save, save data to a data object
  - [x] Make sure the data is saved to local storage.
- [x] Check functionality of the buttons and drop down.
- [x] Make sure user can only enter valid numbers
- [x] Clean up code
