### ISSUE TITLE
Feature: User can see main page

### ISSUE THREAD

**Issue by tangm28** [tangm28/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the main page of the app

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Build out page to look like Wireframe

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749849/148310408-e1eda3fc-261f-4b21-b047-4356e015fb1f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create card for 'Current Training Maxes'
   - [x] In the card, create 4 cards for each of the main lifts: Bench, Squat, Deadlift, OHP
- [ ] Create card for 'Workout Plans'
   - [ ] In the card, create cards when workouts are created
   - [ ] Have button to create new workout
   - [ ] Add functionality later
- [ ] Create card for 'Supplements'
   - [ ] In the card, create cards for supplements
   - [ ] Add functionality later
- [ ] Create card for 'H20'
   - [ ] In the card, Add image of water bottle
   - [ ] Add functionality later
- [ ] Create card for 'Explore Exercises by Muscle Groups'
   - [ ] Add functionality later
- [ ] Create card for 'Measurements'
   - [ ] Add functionality later
