### ISSUE TITLE
Feature: User can edit their Current Training Maxes

### ISSUE THREAD

**Issue by tangm28** [tangm28/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit their Current Training Maxes

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When clicking the edit icon, the user will go to their current training max page.
The page will look similar to the Let's get started page.
User can change the numbers and dropdown selection and update the maxes.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749849/148311649-a318407b-121e-49ec-8d0c-9a793f5b4dd1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When user select icon hide main page to show Current Training Maxes
- [x] Use the 'Let's get started' page
- [x] If User enters this page from edit icon remove the description text and update title to Current Training Maxes
  - [x] Text input box will show current numbers
  - [x] Dropdown will show current measurement selection
- [x] User can update input textbox with valid number
- [x] Use can change dropdown value
- [x] User can select the Update button to update current training maxes
- [x] User can go back to previous screen with the back button at top of screen
- [x] Current training maxes on main page should be updated
- [x] Data object and local storage should keep track of data change
