### ISSUE TITLE
Feature: User can use hamburger menu

### ISSUE THREAD

**Issue by tangm28** [tangm28/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Hamburger functionality is active

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Hamburger menu modal for quick navigation

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749849/148312595-b6c2ceae-bdab-4cc4-b0fa-436c33e59e6c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] User can select hamburger menu at the top left of screen
- [ ] Overlay covers screen except for header
- [ ] Hamburger icon is changed to back button
  - [ ] Back button closes menu
- [ ] Hero image placeholder
- [ ] New User place holder
- [ ] Add edit icon to edit name and image
  - [ ] Add functionality later
- [ ] Add link to Current Training Maxes
- [ ] Add link to Current Workout
- [ ] Add link to Supplements
- [ ] Add link to Daily H20
- [ ] Add link to Explore Exercises
- [ ] Add link to Measurements
