### ISSUE TITLE
Feature: User can explore exercises by muscle group

### ISSUE THREAD

**Issue by tangm28** [tangm28/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can explore exercises by muscle group

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Use can select a muscle group from a drop down and see an image of the muscle they selected
They can see exercises by clicking on the see exercises button
User will go to a page that list all exercises for that muscle
User can select exercise to see a detailed page of the exercise
Detailed page shows user what equipment is required, a basic description, and the muscle that the exercise targets.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93749849/148313387-ee2ef2be-0b30-454c-ab16-04b6c2557833.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create title 'Exercises by Muscle Group
- [ ] Add description
- [ ] Add dropdown with muscle groups collected from API
- [ ] Add button that brings Users to the selected muscle group exercise page
- [ ] Compile list of exercises from API
- [ ] User can select exercise to view detailed information
- [ ] Detailed information page is built using the API
